### ISSUE TITLE
Some batch files cannot be executed

### ISSUE THREAD

**Issue by Leo3418** [njlyf2011/WinBatchTools#2]
### Description
When I downloaded this repository's code in ZIP and unzipped it using WinRAR 5.01 64-bit and 8 Zip 1.2.112.0 under Windows 10 14393.351, some batch files, such as [重命名计算机.bat](https://github.com/njlyf2011/WinBatchTools/blob/master/system/%E9%87%8D%E5%91%BD%E5%90%8D%E8%AE%A1%E7%AE%97%E6%9C%BA.bat), could run without error; others like [提取用户列表.bat](https://github.com/njlyf2011/WinBatchTools/blob/master/system/%E6%8F%90%E5%8F%96%E7%94%A8%E6%88%B7%E5%88%97%E8%A1%A8.cmd) failed to run and returned error messages as the fitst attached screenshot shows.
### Reason
When I opened the unexecutable batch files using Windows Notepad, all separated lines appeared in GitHub webpages concatenated into a single line, as the second attached screenshot shows.  
It is probably because Windows cannot correctly process new lines in files which have been processed by Unix. In Windows, the end of a line has a **carriage return** and a **line feed**; but in Unix, there is only a line feed. ([Reference](http://blog.chinaunix.net/uid-25548639-id-3084300.html))  
This is shown in the third screenshot.

---
### 问题描述
我在Windows 10 14393.351上使用WinRAR 5.01 64位版和8 Zip 1.2.112.0解压从GitHub下载的源码ZIP包后，发现部分批处理，如[重命名计算机.bat](https://github.com/njlyf2011/WinBatchTools/blob/master/system/%E9%87%8D%E5%91%BD%E5%90%8D%E8%AE%A1%E7%AE%97%E6%9C%BA.bat)，可以正常运行；而又有一些批处理，比如[提取用户列表.bat](https://github.com/njlyf2011/WinBatchTools/blob/master/system/%E6%8F%90%E5%8F%96%E7%94%A8%E6%88%B7%E5%88%97%E8%A1%A8.cmd)，无法正常运行，如第一张截图所示。
### 原因
我在Windows记事本下打开不能运行的批处理文件，发现本来在GitHub上看到的有换行的代码全部集中到一行里了。  
具体的原因是Windows无法正确处理Unix下的换行：Windows下需要有**回车**和**换行**才会另起一行，但Unix下只需要一个换行即可。（可参考[这篇文章](http://blog.chinaunix.net/uid-25548639-id-3084300.html)）
如第三张截图所示。

---

![image](https://cloud.githubusercontent.com/assets/14175175/19966933/f3e053b8-a208-11e6-9576-a51e56f93be4.png)
![image](https://cloud.githubusercontent.com/assets/14175175/19966835/7d0bc880-a208-11e6-9403-b642fa64157c.png)
![image](https://cloud.githubusercontent.com/assets/14175175/20036043/4abe4fda-a436-11e6-993e-398042e55d40.png)

**Comment by njlyf2011** [comment]
OK.Thank for you advising.
I will fix it as soon as possible.
